Fix help indentation for starting url.
ragingwind/chrome-launcher-cli pull request #1
Opened 2017-06-24 23:56 UTC by samccone

2017-06-24 23:59 UTC, paulirish requested changes

2017-06-24 23:59 UTC, paulirish commented on src/cli.ts
>    	--port: emote debugging port number to use.
s/emote/Remote/

2017-06-24 23:59 UTC, paulirish commented on src/cli.ts
>  	Examples
and down on L20 i dont think "chrome-launcher --headless" actually would work if i'm reading this right.

2017-06-25 00:08 UTC, paulirish commented on src/cli.ts
>  	Examples
ok ill do these :)

2017-06-25 02:07 UTC, merged

2017-06-25 02:07 UTC, ragingwind commented
Thanks.

2017-06-25 02:12 UTC, ragingwind commented on src/cli.ts
>  	Examples
@paulirish I'll fix it. thanks!